---
title: "R Notebook"
output: html_notebook
---

```{r}
library(diagram)
```


```{r fig.height=12, fig.width=12}
# set margins and multiplot
par(mfrow = c(2, 2))
par(mar = c(0, 0, 0, 0))

# initialise a plot device
openplotmat()

# position of boxes
# 1st column indicates x axis position between 0 and 1
# 2nd column indicates y axis position between 0 and 1
# automatically assigns vertical position
num_of_boxes <- 9
auto_coords = coordinates(num_of_boxes)
vert_pos = rev(auto_coords[,1])
box_pos <- matrix(nrow = num_of_boxes, ncol = 2, data = 0)
box_pos[1,] = c(0.20, vert_pos[1]) # 1st box
box_pos[2,] = c(0.70, vert_pos[2]) # 2nd box
box_pos[3,] = c(0.70, vert_pos[3]) # 3rd box
box_pos[4,] = c(0.70, vert_pos[4]) # etc...
box_pos[5,] = c(0.70, vert_pos[5])
box_pos[6,] = c(0.70, vert_pos[6])
box_pos[7,] = c(0.70, vert_pos[7])
box_pos[8,] = c(0.70, vert_pos[8])
box_pos[9,] = c(0.20, vert_pos[9])

# content of boxes
box_content <- matrix(nrow = num_of_boxes, ncol = 1, data = 0)
box_content[1] = "All patients in MIMIC-III with ICU Stay \n n = 46,476" # 1st box
box_content[2] = "Exclude patients of age < 16 \n n = 7,879" # 2nd box
box_content[3] = "Exclude patients with no ICU Length of Stay <4h \n n = 282" # 3rd box
box_content[4] = "Exclude patients with <4h on ventilation \n n = 24,139" # etc...
box_content[5] = "Exclude patients who die in ICU \n n = 3,391"
box_content[6] = "Exclude patients who die in hospital \n n = 730"
box_content[7] = "Exclude patients without sepsis \n n = 9,971"
box_content[8] = "Exclude patients with >2 desaturations \n n = 4,804"
box_content[9] = "Exclude patients with sepsis \n n = 4,804"

box_content[9] = "Study cohort \n n = 43,597"

# adjust the size of boxes to fit content
box_x <- c(0.20, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.20)
box_y <- c(0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07)

# Draw the arrows
straightarrow(from = c(box_pos[1,1],box_pos[2,2]), to = box_pos[2,], lwd = 1)  
straightarrow(from = c(box_pos[1,1],box_pos[3,2]), to = box_pos[3,], lwd = 1)  
straightarrow(from = c(box_pos[1,1],box_pos[4,2]), to = box_pos[4,], lwd = 1)  
straightarrow(from = c(box_pos[1,1],box_pos[5,2]), to = box_pos[5,], lwd = 1)

straightarrow(from = c(box_pos[1,1],box_pos[6,2]), to = box_pos[6,], lwd = 1)
straightarrow(from = c(box_pos[1,1],box_pos[7,2]), to = box_pos[7,], lwd = 1)
straightarrow(from = c(box_pos[1,1],box_pos[8,2]), to = box_pos[8,], lwd = 1)


straightarrow(from = box_pos[1,], to = box_pos[9,], lwd = 1)

# Draw the boxes
for (i in 1:num_of_boxes) {
  textrect(mid = box_pos[i,], radx = box_x[i], rady = box_y[i], 
           lab = box_content[i], 
           shadow.col = "grey")
}
```

